config/routes.rb
Rails.application.routes.draw do
  resources :gps_trucks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gps_truck.rb
class GpsTruck < ApplicationRecord
    attr_accessor :imei_number, :latitude, :longitude, :engine, :address, :status_text 
    validates :latitude, presence: true

    def initialize(imei_number, latitude, longitude, engine, address, status_text)
        @imei_number = imei_number
        @latitude = latitude
        @longitude = longitude
        @engine = engine
        @address = address
        @status_text = status_text
    end
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gps_trucks_controller.rb
require 'net/http'
class GpsTrucksController < ApplicationController
  before_action :set_gps_truck, only: [:show, :edit, :update, :destroy]

  # GET /gps_trucks
  # GET /gps_trucks.json
  def index
    @gps_trucks = GpsTruck.all
    url = URI.parse('http://client.inditracking.com/API/LatestLocation.aspx?trackerid=67965023197813')
    req = Net::HTTP::Get.new(url.to_s)
    req = Net::HTTP::Get.new(url.to_s)
    res = Net::HTTP.start(url.host, url.port) {|http|
      http.request(req)
    }
    body = JSON.parse(res.body)
    @res = body
    @imei_number = body.first.try(:[],"ImeiNo")
    @latitude = body.first.try(:[],"Latitude")
    @longitude = body.first.try(:[],"Longitude")
    @engine = body.first.try(:[], "Engine")
    @address = body.first.try(:[], "Address")
    @status_text = body.first.try(:[], "StatusText")
    @gps_truck = GpsTruck.new @imei_number, @latitude, @longitude, @engine, @address, @status_text
  end

  # GET /gps_trucks/1
  # GET /gps_trucks/1.json
  def show
  end

  # GET /gps_trucks/new
  def new
    @gps_truck = GpsTruck.new
  end

  # GET /gps_trucks/1/edit
  def edit
  end

  # POST /gps_trucks
  # POST /gps_trucks.json
  def create
    @gps_truck = GpsTruck.new(gps_truck_params)

    respond_to do |format|
      if @gps_truck.save
        format.html { redirect_to @gps_truck, notice: 'Gps truck was successfully created.' }
        format.json { render :show, status: :created, location: @gps_truck }
      else
        format.html { render :new }
        format.json { render json: @gps_truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gps_trucks/1
  # PATCH/PUT /gps_trucks/1.json
  def update
    respond_to do |format|
      if @gps_truck.update(gps_truck_params)
        format.html { redirect_to @gps_truck, notice: 'Gps truck was successfully updated.' }
        format.json { render :show, status: :ok, location: @gps_truck }
      else
        format.html { render :edit }
        format.json { render json: @gps_truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gps_trucks/1
  # DELETE /gps_trucks/1.json
  def destroy
    @gps_truck.destroy
    respond_to do |format|
      format.html { redirect_to gps_trucks_url, notice: 'Gps truck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gps_truck
      @gps_truck = GpsTruck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gps_truck_params
      params.fetch(:gps_truck, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gps_trucks_helper.rb
module GpsTrucksHelper
end

app/views/gps_trucks/_form.html.erb
<%= form_with(model: gps_truck, local: true) do |form| %>
  <% if gps_truck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gps_truck.errors.count, "error") %> prohibited this gps_truck from being saved:</h2>

      <ul>
      <% gps_truck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gps_trucks/edit.html.erb
<h1>Editing Gps Truck</h1>

<%= render 'form', gps_truck: @gps_truck %>

<%= link_to 'Show', @gps_truck %> |
<%= link_to 'Back', gps_trucks_path %>

app/views/gps_trucks/index.html.erb
 <p id="notice"><%= notice %></p>

<h1>Gps Trucks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gps_trucks.each do |gps_truck| %>
      <tr>
        <td><%= link_to 'Show', gps_truck %></td>
        <td><%= link_to 'Edit', edit_gps_truck_path(gps_truck) %></td>
        <td><%= link_to 'Destroy', gps_truck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
  Engine: <%= @gps_truck.engine %>
  <br>
  Address: <%= @gps_truck.address %>
  <br>
  Status Text: <%= @gps_truck.status_text %>
<br>

<%#= link_to 'New Gps Truck', new_gps_truck_path %> 
<div id="map" style="width: 400px; height: 400px"></div>
    <script>
      var my_var = 
      console.log(my_var);
      var latitude = <%= @latitude %>
      var longitude = <%= @longitude%>
      console.log(longitude);
      function initMap() {

        var myLatLng = {lat: latitude, lng: longitude};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 4,
          center: myLatLng
        });

        map.setZoom(15);

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }
    </script>
  <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyABI4whFkeSmgCIkIfjNY_LxR3fsAFXGfo&callback=initMap">
  </script>

app/views/gps_trucks/new.html.erb
<h1>New Gps Truck</h1>

<%= render 'form', gps_truck: @gps_truck %>

<%= link_to 'Back', gps_trucks_path %>

app/views/gps_trucks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_gps_truck_path(@gps_truck) %> |
<%= link_to 'Back', gps_trucks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Interview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>